#!/bin/bash
#
# Script to install GNURadio and dependencies for Sprite receiver on Ubuntu-based systems


# Install prerequisite packages
#
sudo apt-get install gnuradio gnuradio-dev cmake git libboost-all-dev libusb-1.0-0 libusb-1.0-0-dev libfftw3-dev swig python-numpy

# Make a directory to clone all source code into
#
mkdir ~/SpriteRadioSrc

# Install RTL-SDR Driver
#
cd ~/SpriteRadioSrc && git clone --progress git://git.osmocom.org/rtl-sdr.git && cd rtl-sdr && mkdir build && cd build && cmake .. -DINSTALL_UDEV_RULES=ON && make && sudo make install


# Install RTL-SDR GNURadio Block
#
cd ~/SpriteRadioSrc && git clone --progress git://git.osmocom.org/gr-osmosdr && cd gr-osmosdr && git checkout gr3.6 && mkdir build && cd build && cmake .. && make && sudo make install


# Install Sprite GNURadio Blocks
#
cd ~/SpriteRadioSrc && git clone --progress git://github.com/zacinaction/kicksat && cd kicksat/GroundStation/GNURadio/gr-sprite && mkdir build && cd build && cmake .. && make && sudo make install && sudo ldconfig


# Add GNURadio config file telling GRC where to look for new blocks 
# 
if [ ! -d ~/.gnuradio ]; then
	mkdir ~/.gnuradio
fi
echo -e "[grc]\nlocal_blocks_path=/usr/local/share/gnuradio/grc/blocks" >> ~/.gnuradio/config.conf

# Delete downloaded files
#
rm -Rf ~/SpriteRadioSrc

exit 0

